import UIKit

var ilce: String = "Kadıköy"
var kita: String = "Avrupa"
var faks: String = "+90 216 123 45 67"
var postaKodu: Int = 34734
var instaAdresi: String = "@exampleUser"
var calistiginBolum: String = "Yazılım Geliştirme"
var urunMiktari: Int = 50
var musteriSoyadi: String = "Yılmaz"
var odemeMiktari: Double = 1250.75
var dogumTarihi: String = "15/09/1990"
var borc: Double = 450.30
var medeniHal: String = "Evli"
var videoYorumu: String = "Harika bir video!"
var odemeSaati: String = "14:30"
var eftMiktari: Double = 1000.50
var satilanMiktar: Int = 20
var telefonModeli: String = "iPhone 14"
var dergiAdi: String = "Teknoloji Dergisi"
var basimTarihi: String = "01/08/2024"
var zamMiktari: Double = 500.00
var daireSayisi: Int = 3
var enlem: Double = 41.0082
var boylam: Double = 28.9784
var yemekAdi: String = "Pizza"
var urunFiyati: Double = 59.99
var sirket: String = "XYZ Teknoloji A.Ş."
var videoAdi: String = "iPhone İncelemesi"
var muzikSuresi: Double = 3.45  // dakika
var mekanPuani: Double = 4.7
var dosyaAdi: String = "Dokuman.pdf"
var resimFormati: String = "JPEG"
var renk: String = "Mavi"
var renkKodu: String = "#0000FF"
var bilgisayarModeli: String = "MacBook Pro 16\""
var ekranBoyutu: String = "16 inç"
var kullanimSuresi: Int = 30  // dakika
var basinç: Double = 1013.25  // hPa
var etkinlikGunu: String = "23/09/2024"
var odemeGunu: String = "15/09/2024"
var yolculukCikisTarihi: String = "01/10/2024"
var mahalleAdi: String = "Bahçelievler"
var otobusHatti: String = "34A"
var kullanilanDakika: Int = 45
var kargoTakipNo: String = "TR123456789"
var kuponSuresi: Int = 7  // gün
var kuponKodu: String = "INDIRIM2024"
var faturaTarihi: String = "01/09/2024"
