import UIKit

let ilce: String = "Zeytinburnu"
var kita: String = "Avrupa"
var faks: String = "+90 216 123 45 67"
let postaKodu: Int = 34734
var instaAdresi: String = "https://www.instagram.com/tunaybicer/"
var calistiginBolum: String = "Yazılım Geliştirme"
var urunMiktari: Int = 50
let musteriSoyadi: String = "Yılmaz"
var odemeMiktari: Double = 1250.75
let dogumTarihi: String = "15/09/1990"
var borc: Double = 450.30
var medeniHal: String = "Evli"
var videoYorumu: String = "This video changed my life! my wife left me and my boss fired me :("
var odemeSaati: String = "14:30"
var eftMiktari: Double = 1000.50
var satilanMiktar: Int = 20
var telefonModeli: String = "iPhone 5"
var dergiAdi: String = "TIMES"
let basimTarihi: String = "01/08/2024"
var zamMiktari: Double = 50.02
var daireSayisi: Int = 3
let enlem: Double = 41.0082
let boylam: Double = 28.9784
var yemekAdi: String = "Patates Püresi"
var urunFiyati: Double = 59.99
var sirket: String = "Innova"
var videoAdi: String = "Wind Rose • Together We Rise"
let muzikSuresi: Double = 5.03
var mekanPuani: Double = 4.7
var dosyaAdi: String = "Homework1.playground"
var resimFormati: String = "JPEG"
var renk: String = "Mavi"
let renkKodu: String = "#0000FF"
var bilgisayarModeli: String = "MacBook Pro M3 16GB 14\""
var ekranBoyutu: String = "14 inç"
var kullanimSuresi: Int = 30
var basinç: Double = 1013.25
var etkinlikGunu: String = "23/09/2024"
var odemeGunu: String = "15/09/2024"
var yolculukCikisTarihi: String = "01/10/2024"
let mahalleAdi: String = "Nuripaşa"
let otobusHatti: String = "34A"
var kullanilanDakika: Int = 45
let kargoTakipNo: String = "TR123456789"
var kuponSuresi: Int = 7
let kuponKodu: String = "HOSGELDIN25"
var faturaTarihi: String = "01/09/2024"
